services:
  app:
    container_name: "visual-regression-example-app"
    image: "druidfi/drupal-web:php-8.3"
    hostname: "visual-regression-example"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    environment:
      APP_ENV: "${APP_ENV:-local}"
      DRUSH_OPTIONS_URI: "https://visual-regression-example.docker.so"
      SIMPLETEST_BASE_URL: "http://app:8888"
      BROWSERTEST_OUTPUT_BASE_URL: "https://visual-regression-example.docker.so"
      BROWSERTEST_OUTPUT_DIRECTORY: "/app/public/sites/default/files/simpletest"
      WEBROOT: web
      REDIS_HOST: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "visual-regression-example.docker.so:host-gateway"
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`visual-regression-example.docker.so`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
  redis:
    container_name: "visual-regression-example-redis"
    image: redis:7-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    networks:
      - internal
  db:
    container_name: "visual-regression-example-db"
    image: mysql:8
    command:
      - --max_allowed_packet=512M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_swedish_ci
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal
networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_volume:
