services:
  app:
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "${DRUPAL_IMAGE}"
    hostname: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    environment:
      APP_ENV: "${APP_ENV:-local}"
      DRUPAL_ROUTES: "http://${COMPOSE_PROJECT_NAME},https://${DRUPAL_HOSTNAME}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      # To enable xdebug, run `export XDEBUG_ENABLE=true` before (re)starting your project.
      # Optionally, you can add this to your default environments variables to enable or disable
      # xdebug by default (like /etc/environments, ~/.bashrc, or ~/.zshrc).
      XDEBUG_ENABLE: "${XDEBUG_ENABLE:-false}"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-serverName=${DRUPAL_HOSTNAME}}"
      # DOCKERHOST: host.docker.internal
      # Use drush server to run functional tests, so we don't have to care about
      # permission or SSL issues.
      SIMPLETEST_BASE_URL: "http://app:8888"
      BROWSERTEST_OUTPUT_BASE_URL: "https://${DRUPAL_HOSTNAME}"
      BROWSERTEST_OUTPUT_DIRECTORY: "/app/public/sites/default/files/simpletest"
      WEBROOT: web
      REDIS_HOST: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DRUPAL_HOSTNAME}:host-gateway"
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:7-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    networks:
      - internal
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: mysql:8
    command:
      - --max_allowed_packet=512M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_swedish_ci
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal
networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_volume:
