on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md'
    branches-ignore:
      - 'renovate/**'
  push:
    branches:
      - main
env:
  SIMPLETEST_DB: mysql://drupal:drupal@db:3306/drupal
name: Visual regression tests

concurrency:
  group: visual-regression

jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update
        run:  sudo apt update

      - name: Install and start Stonehenge
        run: |
          git clone -b 4.x https://github.com/druidfi/stonehenge.git ~/stonehenge
          cd ~/stonehenge && make up

      - name: Build project
        run: composer install

      - name: Restore files folder
        id: drupal-cache
        uses: actions/cache@v4
        with:
          path: web/sites/default/files
          key: drupal-cache

      - name: Prepare Drupal setup
        run: mkdir web/sites/default/files/styles -p && chmod 777 web/sites/default -R

      - name: Start the project
        run: |
          docker compose up -d --wait
          # Wait for Drupal to respond.
          for i in {1..5}; do docker compose exec app bash -c "drush sqlq 'SHOW TABLES;' -q" && break || sleep 5; done

        # Install the site from existing dump when the cache restoration was successful.
      - name: Install Drupal from existing dump
        if: steps.drupal-cache.outputs.cache-hit == 'true'
        run: |
          docker compose exec app bash -c "mysql --user=drupal --password=drupal --database=drupal --host=db --port=3306 -A < /app/web/sites/default/files/latest.sql"
          docker compose exec app bash -c "drush deploy"

        # Install the site from scratch using existing configuration when we failed to restore the cache.
        # The database is then dumped into the files folder, so we don't have to deal with multiple caches.
        # Set up any default content in this step.
      - name: Install Drupal from scratch
        if: steps.drupal-cache.outputs.cache-hit != 'true'
        run: |
          docker compose exec app bash -c "drush si --existing-config -y"
          docker compose exec app bash -c "drush sql-dump --result-file=/app/web/sites/default/files/latest.sql"

      - name: Node setup
        run: |
          export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install && npm install && npx playwright install

      - name: Generate reference images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download -n bitmaps -D web/backstop/bitmaps_reference || true

          # Always update reference images when the pull request is merged to main branch.
          if [ ! -d "web/backstop/bitmaps_reference" ] || [ "$GITHUB_REF" == "refs/heads/main" ]; then
            GENERATE_REFERENCES=1
          fi

          # Regenerate reference images
          if [ "$GENERATE_REFERENCES" == "1" ]; then
            node web/backstop/config.js reference
            echo "UPLOAD_BITMAP=1" >> $GITHUB_ENV
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ env.UPLOAD_BITMAP == '1' }}
        with:
          name: bitmaps
          path: web/backstop/bitmaps_reference
          overwrite: true
          compression-level: 0

      - name: Run tests
        id: run-tests
        # Skip tests when run against the 'main' branch since we're generating
        # reference images and tests should never fail.
        if: github.ref != 'refs/heads/main'
        run: |
          if ! node backstop/config.js test; then
            echo "result=:warning: Visual regression found! Please check if this change is wanted or accidental. " >> $GITHUB_OUTPUT
          else
            echo "result=✅ Tests passed!" >> $GITHUB_OUTPUT
          fi
          echo "report_url=You can check the output here: https://tuutti.github.io/visual-regression-example/pull/${{ github.event.pull_request.number }}/html_report/" >> $GITHUB_OUTPUT

      - name: Export container logs
        run: docker compose logs app > /tmp/container.log

      - name: Deploy to PR preview
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref != 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/backstop/
          destination_dir: pull/${{github.event.number}}

      - name: Update comment
        if: github.ref != 'refs/heads/main'
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: status
          pr_number: ${{ github.event.number }}
          message: "${{join(steps.run-tests.outputs.*, '  ')}}"

      - name: Upload container logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: container-log
          path: /tmp/container.log
          retention-days: 1
